//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.SNES.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MushROMs.SNES.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The address was outside the range of the data..
        /// </summary>
        internal static string ErrorAddressOutOfRange {
            get {
                return ResourceManager.GetString("ErrorAddressOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a valid tile arrange format..
        /// </summary>
        internal static string ErrorArrangeFormat {
            get {
                return ResourceManager.GetString("ErrorArrangeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editor data is null..
        /// </summary>
        internal static string ErrorEditorDataNull {
            get {
                return ResourceManager.GetString("ErrorEditorDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file data is null..
        /// </summary>
        internal static string ErrorFileData {
            get {
                return ResourceManager.GetString("ErrorFileData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graphics file formats is unknown or not supported..
        /// </summary>
        internal static string ErrorGFXFileFormatUnknown {
            get {
                return ResourceManager.GetString("ErrorGFXFileFormatUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graphics data has not been initialized..
        /// </summary>
        internal static string ErrorGFXNotInitialized {
            get {
                return ResourceManager.GetString("ErrorGFXNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid gradient style value..
        /// </summary>
        internal static string ErrorGradientStyle {
            get {
                return ResourceManager.GetString("ErrorGradientStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of data is not a valid size for the specified format..
        /// </summary>
        internal static string ErrorInvalidFileDataSize {
            get {
                return ResourceManager.GetString("ErrorInvalidFileDataSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of GFX tiles is less than or equal to zero..
        /// </summary>
        internal static string ErrorNumGFXTiles {
            get {
                return ResourceManager.GetString("ErrorNumGFXTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of colors is less than or equal to zero..
        /// </summary>
        internal static string ErrorNumPaletteTiles {
            get {
                return ResourceManager.GetString("ErrorNumPaletteTiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The palette data has not been initialized..
        /// </summary>
        internal static string ErrorPaleteNotInitialized {
            get {
                return ResourceManager.GetString("ErrorPaleteNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size of data is not large enough to support specified number of colors..
        /// </summary>
        internal static string ErrorPaletteDataTooSmall {
            get {
                return ResourceManager.GetString("ErrorPaletteDataTooSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The palette file format is unknown or not supported..
        /// </summary>
        internal static string ErrorPaletteFileFormatUnknown {
            get {
                return ResourceManager.GetString("ErrorPaletteFileFormatUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pixel array size does not match the size of the drawing data..
        /// </summary>
        internal static string ErrorPixelDataSizeMismatch {
            get {
                return ResourceManager.GetString("ErrorPixelDataSizeMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNES9x save state is an unknown format..
        /// </summary>
        internal static string ErrorS9XFormat {
            get {
                return ResourceManager.GetString("ErrorS9XFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown SNES9x version..
        /// </summary>
        internal static string ErrorS9XVersion {
            get {
                return ResourceManager.GetString("ErrorS9XVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save data as a save state if it was not originally a save state. There is no referenced save state data to include..
        /// </summary>
        internal static string ErrorSaveStateFile {
            get {
                return ResourceManager.GetString("ErrorSaveStateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot get size for save state files..
        /// </summary>
        internal static string ErrorSaveStateSize {
            get {
                return ResourceManager.GetString("ErrorSaveStateSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pixel data pointer is null..
        /// </summary>
        internal static string ErrorScan0Null {
            get {
                return ResourceManager.GetString("ErrorScan0Null", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two selections do not match in size..
        /// </summary>
        internal static string ErrorSelectionsMismatch {
            get {
                return ResourceManager.GetString("ErrorSelectionsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save data as an SNES ROM if it was not originally a ROM. There is no referenced ROM data to include..
        /// </summary>
        internal static string ErrorSNESFile {
            get {
                return ResourceManager.GetString("ErrorSNESFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file does not have the proper header for a SNES Tile Layer Pro Palette file..
        /// </summary>
        internal static string ErrorTPLFormat {
            get {
                return ResourceManager.GetString("ErrorTPLFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All valid Palette files.
        /// </summary>
        internal static string FilterOptionsAll {
            get {
                return ResourceManager.GetString("FilterOptionsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary files.
        /// </summary>
        internal static string FilterOptionsBIN {
            get {
                return ResourceManager.GetString("FilterOptionsBIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YY-CHR raw graphics files.
        /// </summary>
        internal static string FilterOptionsCHR {
            get {
                return ResourceManager.GetString("FilterOptionsCHR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNES9x Debugger palette dump.
        /// </summary>
        internal static string FilterOptionsDMP {
            get {
                return ResourceManager.GetString("FilterOptionsDMP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunar Magic Palette files.
        /// </summary>
        internal static string FilterOptionsMW3 {
            get {
                return ResourceManager.GetString("FilterOptionsMW3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAL Palette files.
        /// </summary>
        internal static string FilterOptionsPAL {
            get {
                return ResourceManager.GetString("FilterOptionsPAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SNES9x v1.53/1.51 save state files.
        /// </summary>
        internal static string FilterOptionsS9X {
            get {
                return ResourceManager.GetString("FilterOptionsS9X", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super NES ROM files.
        /// </summary>
        internal static string FilterOptionsSNS {
            get {
                return ResourceManager.GetString("FilterOptionsSNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile Layer Pro files.
        /// </summary>
        internal static string FilterOptionsTPL {
            get {
                return ResourceManager.GetString("FilterOptionsTPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZSNES v1.51 save state files.
        /// </summary>
        internal static string FilterOptionsZST {
            get {
                return ResourceManager.GetString("FilterOptionsZST", resourceCulture);
            }
        }
    }
}
