//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.SNESControls.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int PaletteDashLength1 {
            get {
                return ((int)(this["PaletteDashLength1"]));
            }
            set {
                this["PaletteDashLength1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int PaletteDashLength2 {
            get {
                return ((int)(this["PaletteDashLength2"]));
            }
            set {
                this["PaletteDashLength2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color PaletteDashColor1 {
            get {
                return ((global::System.Drawing.Color)(this["PaletteDashColor1"]));
            }
            set {
                this["PaletteDashColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color PaletteDashColor2 {
            get {
                return ((global::System.Drawing.Color)(this["PaletteDashColor2"]));
            }
            set {
                this["PaletteDashColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int PaletteBGSize {
            get {
                return ((int)(this["PaletteBGSize"]));
            }
            set {
                this["PaletteBGSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color PaletteBGColor1 {
            get {
                return ((global::System.Drawing.Color)(this["PaletteBGColor1"]));
            }
            set {
                this["PaletteBGColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color PaletteBGColor2 {
            get {
                return ((global::System.Drawing.Color)(this["PaletteBGColor2"]));
            }
            set {
                this["PaletteBGColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float GFXDashLength1 {
            get {
                return ((float)(this["GFXDashLength1"]));
            }
            set {
                this["GFXDashLength1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public float GFXDashLength2 {
            get {
                return ((float)(this["GFXDashLength2"]));
            }
            set {
                this["GFXDashLength2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GFXDashColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GFXDashColor1"]));
            }
            set {
                this["GFXDashColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GFXDashColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GFXDashColor2"]));
            }
            set {
                this["GFXDashColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int GFXBGSize {
            get {
                return ((int)(this["GFXBGSize"]));
            }
            set {
                this["GFXBGSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color GFXBGColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GFXBGColor1"]));
            }
            set {
                this["GFXBGColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color GFXBGColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GFXBGColor2"]));
            }
            set {
                this["GFXBGColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int PaletteZoomScale {
            get {
                return ((int)(this["PaletteZoomScale"]));
            }
            set {
                this["PaletteZoomScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FirstTime {
            get {
                return ((bool)(this["FirstTime"]));
            }
            set {
                this["FirstTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16, 16")]
        public global::System.Drawing.Size PaletteViewSize {
            get {
                return ((global::System.Drawing.Size)(this["PaletteViewSize"]));
            }
            set {
                this["PaletteViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GFXZoomScale {
            get {
                return ((int)(this["GFXZoomScale"]));
            }
            set {
                this["GFXZoomScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SNES_4BPP")]
        public global::MushROMs.LunarCompress.GraphicsFormats GraphicsFormat {
            get {
                return ((global::MushROMs.LunarCompress.GraphicsFormats)(this["GraphicsFormat"]));
            }
            set {
                this["GraphicsFormat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16, 8")]
        public global::System.Drawing.Size GFXViewSize {
            get {
                return ((global::System.Drawing.Size)(this["GFXViewSize"]));
            }
            set {
                this["GFXViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8")]
        public int GFXTileZoomScale {
            get {
                return ((int)(this["GFXTileZoomScale"]));
            }
            set {
                this["GFXTileZoomScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8, 8")]
        public global::System.Drawing.Size GFXTileViewSize {
            get {
                return ((global::System.Drawing.Size)(this["GFXTileViewSize"]));
            }
            set {
                this["GFXTileViewSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GFXTileBGSize {
            get {
                return ((int)(this["GFXTileBGSize"]));
            }
            set {
                this["GFXTileBGSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Gray")]
        public global::System.Drawing.Color GFXTileBGColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GFXTileBGColor1"]));
            }
            set {
                this["GFXTileBGColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Silver")]
        public global::System.Drawing.Color GFXTileBGColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GFXTileBGColor2"]));
            }
            set {
                this["GFXTileBGColor2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GFXTileDashLength1 {
            get {
                return ((int)(this["GFXTileDashLength1"]));
            }
            set {
                this["GFXTileDashLength1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int GFXTileDashLength2 {
            get {
                return ((int)(this["GFXTileDashLength2"]));
            }
            set {
                this["GFXTileDashLength2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color GFXTileDashColor1 {
            get {
                return ((global::System.Drawing.Color)(this["GFXTileDashColor1"]));
            }
            set {
                this["GFXTileDashColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color GFXTileDashColor2 {
            get {
                return ((global::System.Drawing.Color)(this["GFXTileDashColor2"]));
            }
            set {
                this["GFXTileDashColor2"] = value;
            }
        }
    }
}
