//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.Editors.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MushROMs.Editors.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alpha component is outside of valid range. Value must be less than 0 or greater than 255..
        /// </summary>
        public static string ErrorAlphaRange {
            get {
                return ResourceManager.GetString("ErrorAlphaRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blue component is outside of valid range. Value must be less than 0 or greater than 255..
        /// </summary>
        public static string ErrorBlueRange {
            get {
                return ResourceManager.GetString("ErrorBlueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective percent value is outside of valid range. Value must be less than 0 or greater than 100..
        /// </summary>
        public static string ErrorColorizeEff {
            get {
                return ResourceManager.GetString("ErrorColorizeEff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue rotation value is outside of valid range. Value must be less than 0 or greater than 360..
        /// </summary>
        public static string ErrorColorizeHue {
            get {
                return ResourceManager.GetString("ErrorColorizeHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosity percent value is outside of valid range. Value must be less than 0 or greater than 100..
        /// </summary>
        public static string ErrorColorizeLum {
            get {
                return ResourceManager.GetString("ErrorColorizeLum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation percent value is outside of valid range. Value must be less than 0 or greater than 100..
        /// </summary>
        public static string ErrorColorizeSat {
            get {
                return ResourceManager.GetString("ErrorColorizeSat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyan component is outside of valid range. Value must be less than 0 or greater than 255..
        /// </summary>
        public static string ErrorCyanRange {
            get {
                return ResourceManager.GetString("ErrorCyanRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data is null.
        /// </summary>
        public static string ErrorDataNull {
            get {
                return ResourceManager.GetString("ErrorDataNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editor data is read only..
        /// </summary>
        public static string ErrorDataReadOnly {
            get {
                return ResourceManager.GetString("ErrorDataReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Names list and extensions list do not match in size..
        /// </summary>
        public static string ErrorFilterMismatch {
            get {
                return ResourceManager.GetString("ErrorFilterMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green component is outside of valid range. Value must be less than 0 or greater than 255..
        /// </summary>
        public static string ErrorGreenRange {
            get {
                return ResourceManager.GetString("ErrorGreenRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue value is outside of valid range. Value must be less than 0 or greater than 360..
        /// </summary>
        public static string ErrorHueRange {
            get {
                return ResourceManager.GetString("ErrorHueRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval is less than or equal to zero..
        /// </summary>
        public static string ErrorIntervalNotPositive {
            get {
                return ResourceManager.GetString("ErrorIntervalNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is less than zero..
        /// </summary>
        public static string ErrorLengthNegative {
            get {
                return ResourceManager.GetString("ErrorLengthNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length is less than or equal to zero..
        /// </summary>
        public static string ErrorLengthNotPositive {
            get {
                return ResourceManager.GetString("ErrorLengthNotPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosity value is outside of valid range. Value must be less than 0 or greater than 240..
        /// </summary>
        public static string ErrorLumRange {
            get {
                return ResourceManager.GetString("ErrorLumRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Magenta component is outside of valid range. Value must be less than 0 or greater than 255..
        /// </summary>
        public static string ErrorMagentaRange {
            get {
                return ResourceManager.GetString("ErrorMagentaRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map size has a width or height component that is less than or equal to zero..
        /// </summary>
        public static string ErrorMapSize {
            get {
                return ResourceManager.GetString("ErrorMapSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hue rotation value is outside of valid range. Value must be less than -180 or greater than 180..
        /// </summary>
        public static string ErrorModifyHue {
            get {
                return ResourceManager.GetString("ErrorModifyHue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luminosity percent value is outside of valid range. Value must be less than -100 or greater than 100..
        /// </summary>
        public static string ErrorModifyLum {
            get {
                return ResourceManager.GetString("ErrorModifyLum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation percent value is outside of valid range. Value must be less than -100 or greater than 100..
        /// </summary>
        public static string ErrorModifySat {
            get {
                return ResourceManager.GetString("ErrorModifySat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One of the components has a negative value..
        /// </summary>
        public static string ErrorNegativeWeight {
            get {
                return ResourceManager.GetString("ErrorNegativeWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No extensions exist in for this filter..
        /// </summary>
        public static string ErrorNoExtensions {
            get {
                return ResourceManager.GetString("ErrorNoExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No names are present..
        /// </summary>
        public static string ErrorNoFilterNames {
            get {
                return ResourceManager.GetString("ErrorNoFilterNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editor does not have file data..
        /// </summary>
        public static string ErrorNotFile {
            get {
                return ResourceManager.GetString("ErrorNotFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The base type value provided is not recognized..
        /// </summary>
        public static string ErrorNumberBase {
            get {
                return ResourceManager.GetString("ErrorNumberBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offset is less than zero..
        /// </summary>
        public static string ErrorOffsetNegative {
            get {
                return ResourceManager.GetString("ErrorOffsetNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red component is outside of valid range. Value must be less than 0 or greater than 255..
        /// </summary>
        public static string ErrorRedRange {
            get {
                return ResourceManager.GetString("ErrorRedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturation value is outside of valid range. Value must be less than 0 or greater than 240..
        /// </summary>
        public static string ErrorSatRange {
            get {
                return ResourceManager.GetString("ErrorSatRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is not a valid scroll end value..
        /// </summary>
        public static string ErrorScrollEnd {
            get {
                return ResourceManager.GetString("ErrorScrollEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tile size has a width or height component that is less than or equal to zero..
        /// </summary>
        public static string ErrorTileSize {
            get {
                return ResourceManager.GetString("ErrorTileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View size has a width or height component that is less than or equal to zero..
        /// </summary>
        public static string ErrorViewSize {
            get {
                return ResourceManager.GetString("ErrorViewSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch is null..
        /// </summary>
        public static string ErrorWatchNull {
            get {
                return ResourceManager.GetString("ErrorWatchNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yellow component is outside of valid range. Value must be less than 0 or greater than 255..
        /// </summary>
        public static string ErrorYellowRange {
            get {
                return ResourceManager.GetString("ErrorYellowRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom size has a width or height component that is less than or equal to zero..
        /// </summary>
        public static string ErrorZoomSize {
            get {
                return ResourceManager.GetString("ErrorZoomSize", resourceCulture);
            }
        }
    }
}
